# Dependencies
markdown:        kramdown
highlighter:     pygments

# Permalinks
permalink:           pretty
relative_permalinks: false

# Setup
title:            Ritajit Kundu
tagline:          'I learn physics just for fun'
description:      'This is the website of Ritajit Kundu'
baseurl:          /

author:           'Ritajit Kundu'
name:           'Ritajit Kndu'
url:            https://twitter.com/psyc_eros

#paginate:         5

# Custom vars
version:          2.1.0

github:      
  repo:           https://github.com/poole/hyde
